### ISSUE TITLE
Pconst_string changed type in OCaml 4.11

### ISSUE THREAD

**Issue by rwmjones** [gildor478/ocaml-gettext#8]
In https://github.com/ocaml/ocaml/commit/abc53d1a6eab81beeb00afb2f980f89a84f6fa81 `Pconst_string` added an extra `Loc.t` parameter.  This breaks gettext.

The fix is quite simple - change all places where we have `Pconst_string (something, _)` to `Pconst_string (something, _, _)`, and this is what I have done in the Fedora package.  However this will of course break people using OCaml <= 4.10, and I don't know how to make it work for both.

**Comment by gildor478** [comment]
I suppose we can only release it for OCaml 4.10+ and add a constraint like that in OPAM. It should be OK with old versions.

**Comment by rwmjones** [comment]
OCaml >= 4.11 :-)
